In [1]:
import pandas as pd

In [2]:
df= pd.read_csv(r"D:\vs code\pandas\weather\data\dehradun 2015-01-01 to 2015-12-31.csv")

In [3]:
df.columns

Index(['name', 'datetime', 'tempmax', 'tempmin', 'temp', 'feelslikemax',
       'feelslikemin', 'feelslike', 'dew', 'humidity', 'precip', 'precipprob',
       'precipcover', 'preciptype', 'snow', 'snowdepth', 'windgust',
       'windspeed', 'winddir', 'sealevelpressure', 'cloudcover', 'visibility',
       'solarradiation', 'solarenergy', 'uvindex', 'severerisk', 'sunrise',
       'sunset', 'moonphase', 'conditions', 'description', 'icon', 'stations'],
      dtype='str')

In [ ]:
df.info()   # gives Structure- Data types and null values

<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              365 non-null    str
 1   datetime          365 non-null    str
 2   tempmax           365 non-null    float64
 3   tempmin           365 non-null    float64
 4   temp              365 non-null    float64
 5   feelslikemax      365 non-null    float64
 6   feelslikemin      365 non-null    float64
 7   feelslike         365 non-null    float64
 8   dew               365 non-null    float64
 9   humidity          365 non-null    float64
 10  precip            365 non-null    float64
 11  precipprob        365 non-null    int64
 12  precipcover       365 non-null    float64
 13  preciptype        151 non-null    str
 14  snow              365 non-null    int64
 15  snowdepth         365 non-null    int64
 16  windgust          365 non-null    float64
 17  windspeed         365 non-null    float64
 18  winddir           365 non-null    float64
 19  sealevelpressure  365 non-null    float64
 20  cloudcover        365 non-null    float64
 21  visibility        365 non-null    float64
 22  solarradiation    365 non-null    float64
 23  solarenergy       365 non-null    float64
 24  uvindex           365 non-null    int64
 25  severerisk        0 non-null      float64
 26  sunrise           365 non-null    str
 27  sunset            365 non-null    str
 28  moonphase         365 non-null    float64
 29  conditions        365 non-null    str
 30  description       365 non-null    str
 31  icon              365 non-null    str
 32  stations          365 non-null    str
dtypes: float64(20), int64(4), str(9)
memory usage: 144.9 KB

In [ ]:
df["datetime"].head() # view data-first five rows

0    2015-01-01
1    2015-01-02
2    2015-01-03
3    2015-01-04
4    2015-01-05
Name: datetime, dtype: str

Phase1: Understanding data

In [ ]:
df.head()   #give first five rows

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
0,dehradun,2015-01-01,23.6,8.1,15.1,23.6,8.1,15.1,3.1,48.1,...,12.6,6,NaN,2015-01-01T07:14:23,2015-01-01T17:27:59,0.36,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"42111099999,remote"
1,dehradun,2015-01-02,19.7,10.1,14.4,19.7,10.1,14.4,7.3,65.3,...,8.9,4,NaN,2015-01-02T07:14:37,2015-01-02T17:28:42,0.40,"Rain, Partially cloudy",Partly cloudy throughout the day with rain in ...,rain,"42111099999,remote"
2,dehradun,2015-01-03,17.6,10.9,13.4,17.6,10.9,13.4,10.5,83.2,...,7.9,4,NaN,2015-01-03T07:14:50,2015-01-03T17:29:26,0.43,"Rain, Partially cloudy",Partly cloudy throughout the day with morning ...,rain,"42111099999,remote"
3,dehradun,2015-01-04,19.3,8.4,13.0,19.3,7.3,12.8,8.0,74.5,...,12.7,6,NaN,2015-01-04T07:15:01,2015-01-04T17:30:10,0.47,"Rain, Partially cloudy",Partly cloudy throughout the day with early mo...,rain,"42111099999,remote"
4,dehradun,2015-01-05,22.2,4.5,11.8,22.2,2.6,11.4,3.0,60.4,...,13.8,6,NaN,2015-01-05T07:15:11,2015-01-05T17:30:55,0.50,Clear,Clear conditions throughout the day.,clear-day,"42111099999,remote"

In [ ]:
df.columns  #give names of all columns in a list

Index(['name', 'datetime', 'tempmax', 'tempmin', 'temp', 'feelslikemax',
       'feelslikemin', 'feelslike', 'dew', 'humidity', 'precip', 'precipprob',
       'precipcover', 'preciptype', 'snow', 'snowdepth', 'windgust',
       'windspeed', 'winddir', 'sealevelpressure', 'cloudcover', 'visibility',
       'solarradiation', 'solarenergy', 'uvindex', 'severerisk', 'sunrise',
       'sunset', 'moonphase', 'conditions', 'description', 'icon', 'stations'],
      dtype='str')

In [11]:
df.shape    #give the count of rows and columns

(365, 33)

In [17]:
df.info()  # gives a summary of the DataFrame.

<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              365 non-null    str
 1   datetime          365 non-null    str
 2   tempmax           365 non-null    float64
 3   tempmin           365 non-null    float64
 4   temp              365 non-null    float64
 5   feelslikemax      365 non-null    float64
 6   feelslikemin      365 non-null    float64
 7   feelslike         365 non-null    float64
 8   dew               365 non-null    float64
 9   humidity          365 non-null    float64
 10  precip            365 non-null    float64
 11  precipprob        365 non-null    int64
 12  precipcover       365 non-null    float64
 13  preciptype        151 non-null    str
 14  snow              365 non-null    int64
 15  snowdepth         365 non-null    int64
 16  windgust          365 non-null    float64
 17  windspeed         365 non-null    float64
 18  winddir           365 non-null    float64
 19  sealevelpressure  365 non-null    float64
 20  cloudcover        365 non-null    float64
 21  visibility        365 non-null    float64
 22  solarradiation    365 non-null    float64
 23  solarenergy       365 non-null    float64
 24  uvindex           365 non-null    int64
 25  severerisk        0 non-null      float64
 26  sunrise           365 non-null    str
 27  sunset            365 non-null    str
 28  moonphase         365 non-null    float64
 29  conditions        365 non-null    str
 30  description       365 non-null    str
 31  icon              365 non-null    str
 32  stations          365 non-null    str
dtypes: float64(20), int64(4), str(9)
memory usage: 144.9 KB

In [23]:
df.describe()

,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,precip,precipprob,...,windspeed,winddir,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,moonphase
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,...,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,0.0,365.000000
mean,29.634521,17.052877,22.798356,30.605205,16.950411,23.109863,12.824658,58.719726,4.895342,41.369863,...,16.617534,236.565753,1009.760822,31.311233,2.827397,227.794521,19.675890,7.704110,NaN,0.481151
std,6.236750,6.178127,6.350677,6.901218,6.372117,6.671348,7.124362,16.426665,14.204523,49.317180,...,5.086447,74.423955,6.719839,25.262859,0.801588,68.079923,5.890952,1.675653,NaN,0.285451
min,14.900000,4.300000,10.500000,14.900000,2.600000,9.900000,-1.200000,20.300000,0.000000,0.000000,...,7.600000,0.700000,995.600000,0.000000,1.000000,44.900000,3.800000,2.000000,NaN,0.000000
25%,25.500000,12.100000,17.900000,25.500000,12.100000,17.900000,7.600000,49.200000,0.000000,0.000000,...,12.600000,201.700000,1003.600000,9.000000,2.300000,167.800000,14.500000,6.000000,NaN,0.250000
50%,29.900000,18.100000,24.400000,31.000000,18.100000,24.200000,11.500000,56.300000,0.000000,0.000000,...,15.800000,267.600000,1010.500000,25.400000,2.800000,233.800000,20.200000,8.000000,NaN,0.480000
75%,32.500000,22.700000,27.300000,36.400000,22.700000,28.800000,19.400000,70.500000,2.000000,100.000000,...,19.400000,286.100000,1015.700000,48.200000,3.300000,286.000000,24.700000,9.000000,NaN,0.720000
max,43.600000,27.700000,35.300000,51.700000,29.400000,34.400000,24.600000,92.500000,113.000000,100.000000,...,35.600000,351.800000,1021.500000,95.900000,9.100000,351.000000,30.300000,10.000000,NaN,0.980000

Phase 2: Selecting Data

In [30]:
pd.set_option("display.max_rows",None)  #tells pandas to display everything 
df["temp"].head()   # displayes only 5 top rows of temp 
df["temp"]  #gives all rows data

0      15.1
1      14.4
2      13.4
3      13.0
4      11.8
5      11.6
6      12.0
7      12.4
8      12.2
9      10.9
10     11.2
11     11.6
12     13.6
13     11.4
14     11.9
15     13.3
16     13.0
17     12.4
18     12.0
19     12.5
20     12.1
21     11.4
22     12.5
23     13.0
24     12.4
25     12.6
26     12.7
27     11.8
28     11.2
29     10.6
30     11.7
31     13.8
32     15.0
33     15.0
34     14.7
35     14.4
36     14.2
37     14.6
38     15.8
39     15.6
40     15.5
41     14.9
42     15.2
43     15.0
44     17.1
45     18.2
46     17.9
47     18.8
48     18.7
49     19.7
50     19.6
51     19.2
52     19.5
53     20.4
54     20.9
55     19.2
56     17.6
57     16.5
58     17.4
59     14.5
60     13.6
61     13.7
62     13.6
63     15.6
64     16.8
65     17.2
66     16.4
67     15.9
68     17.2
69     18.2
70     19.0
71     19.5
72     19.8
73     17.7
74     18.1
75     18.3
76     17.8
77     19.1
78     21.0
79     21.7
80     22.5
81     23.2
82     24.4
83     25.2
84     25.4
85     25.6
86     25.2
87     22.3
88     19.1
89     21.1
90     22.3
91     23.8
92     21.6
93     19.5
94     20.7
95     22.2
96     20.8
97     21.2
98     22.4
99     24.1
100    25.4
101    24.6
102    23.6
103    23.2
104    23.3
105    22.8
106    24.4
107    26.1
108    28.3
109    28.8
110    28.2
111    26.8
112    28.3
113    28.8
114    27.6
115    25.4
116    27.0
117    27.9
118    27.1
119    28.4
120    27.6
121    27.2
122    27.4
123    28.1
124    29.5
125    30.5
126    31.5
127    31.4
128    31.7
129    31.9
130    31.9
131    29.9
132    29.4
133    28.9
134    29.0
135    29.5
136    30.4
137    32.0
138    32.6
139    31.3
140    32.1
141    32.3
142    33.5
143    34.3
144    34.4
145    33.9
146    32.5
147    32.4
148    32.9
149    33.3
150    32.4
151    31.5
152    30.9
153    31.0
154    32.5
155    32.1
156    32.0
157    33.0
158    34.5
159    35.3
160    33.4
161    34.5
162    34.0
163    32.4
164    29.4
165    30.2
166    31.9
167    32.5
168    32.9
169    33.4
170    30.3
171    30.7
172    31.2
173    31.8
174    30.1
175    26.3
176    28.9
177    30.2
178    30.8
179    28.7
180    28.7
181    29.6
182    29.3
183    30.5
184    30.6
185    29.4
186    28.1
187    27.1
188    27.9
189    28.3
190    26.5
191    25.1
192    26.1
193    26.8
194    27.6
195    27.9
196    27.6
197    26.8
198    27.4
199    27.4
200    27.2
201    27.6
202    26.7
203    27.0
204    27.1
205    27.6
206    27.3
207    27.2
208    27.0
209    26.9
210    27.3
211    26.6
212    26.0
213    26.1
214    27.3
215    27.8
216    27.6
217    27.1
218    25.3
219    25.6
220    25.9
221    27.6
222    27.6
223    27.1
224    27.5
225    27.6
226    27.5
227    26.6
228    26.8
229    26.9
230    26.3
231    25.8
232    25.8
233    25.3
234    25.4
235    25.9
236    26.4
237    27.1
238    27.1
239    26.7
240    26.9
241    26.6
242    26.0
243    25.8
244    25.7
245    25.9
246    25.9
247    25.7
248    25.6
249    25.7
250    25.7
251    26.1
252    26.3
253    26.7
254    26.8
255    26.4
256    26.8
257    26.8
258    26.9
259    26.9
260    26.5
261    26.1
262    26.8
263    26.9
264    26.5
265    24.6
266    23.7
267    23.7
268    24.5
269    24.9
270    24.6
271    25.0
272    25.4
273    25.6
274    25.4
275    25.1
276    24.8
277    24.9
278    24.7
279    25.3
280    25.2
281    25.1
282    25.0
283    24.9
284    24.8
285    24.2
286    23.0
287    23.1
288    23.2
289    23.6
290    23.9
291    24.0
292    24.3
293    22.8
294    21.8
295    22.0
296    22.8
297    22.7
298    21.3
299    20.8
300    19.2
301    19.9
302    19.7
303    20.8
304    21.1
305    21.0
306    20.5
307    20.6
308    20.9
309    20.2
310    20.1
311    20.0
312    20.6
313    20.5
314    19.7
315    19.4
316    20.5
317    20.8
318    20.3
319    19.7
320    18.9
321    18.3
322    18.6
323    19.0
324    19.4
325    19.4
326    18.9
327    19.1
328    18.5
329    18.9
330    17.8
331    18.4
332    18.3
333    19.0
334    18.8
335    17.6
336    16.9
337    16.0
338    16.3
339    16.1
340    16.1
341    16.3
342    15.3
343    16.9
344    15.4
345    14.9
346    14.0
347    13.4
348    12.6
349    13.5
350    12.4
351    12.1
352    12.4
353    12.1
354    11.5
355    12.1
356    11.3
357    10.5
358    10.7
359    12.6
360    14.5
361    15.8
362    15.3
363    15.2
364    14.7
Name: temp, dtype: float64

In [ ]:
df["temp"].tail(10)  #gives last 5 rows, give a number in parenthesis of tail and it will give that many rows

355    12.1
356    11.3
357    10.5
358    10.7
359    12.6
360    14.5
361    15.8
362    15.3
363    15.2
364    14.7
Name: temp, dtype: float64

In [ ]:
df["temp"].sample(4)    #it selects random rows and tells their index and value

107    26.1
55     19.2
87     22.3
175    26.3
Name: temp, dtype: float64

In [36]:
type(df["temp"])

pandas.Series

In [37]:
type(df)

pandas.DataFrame

In [38]:
df["temp"].mean()

np.float64(22.79835616438356)

In [ ]:
df[["datetime","temp"]].head()  #selects 2 columns and merges them their type is dataframe not series

     datetime  temp
0  2015-01-01  15.1
1  2015-01-02  14.4
2  2015-01-03  13.4
3  2015-01-04  13.0
4  2015-01-05  11.8

In [42]:
type(df[["datetime", "temp"]])

pandas.DataFrame

Filtering Rows

In [43]:
df["temp"]>30

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125     True
126     True
127     True
128     True
129     True
130     True
131    False
132    False
133    False
134    False
135    False
136     True
137     True
138     True
139     True
140     True
141     True
142     True
143     True
144     True
145     True
146     True
147     True
148     True
149     True
150     True
151     True
152     True
153     True
154     True
155     True
156     True
157     True
158     True
159     True
160     True
161     True
162     True
163     True
164    False
165     True
166     True
167     True
168     True
169     True
170     True
171     True
172     True
173     True
174     True
175    False
176    False
177     True
178     True
179    False
180    False
181    False
182    False
183     True
184     True
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
205    False
206    False
207    False
208    False
209    False
210    False
211    False
212    False
213    False
214    False
215    False
216    False
217    False
218    False
219    False
220    False
221    False
222    False
223    False
224    False
225    False
226    False
227    False
228    False
229    False
230    False
231    False
232    False
233    False
234    False
235    False
236    False
237    False
238    False
239    False
240    False
241    False
242    False
243    False
244    False
245    False
246    False
247    False
248    False
249    False
250    False
251    False
252    False
253    False
254    False
255    False
256    False
257    False
258    False
259    False
260    False
261    False
262    False
263    False
264    False
265    False
266    False
267    False
268    False
269    False
270    False
271    False
272    False
273    False
274    False
275    False
276    False
277    False
278    False
279    False
280    False
281    False
282    False
283    False
284    False
285    False
286    False
287    False
288    False
289    False
290    False
291    False
292    False
293    False
294    False
295    False
296    False
297    False
298    False
299    False
300    False
301    False
302    False
303    False
304    False
305    False
306    False
307    False
308    False
309    False
310    False
311    False
312    False
313    False
314    False
315    False
316    False
317    False
318    False
319    False
320    False
321    False
322    False
323    False
324    False
325    False
326    False
327    False
328    False
329    False
330    False
331    False
332    False
333    False
334    False
335    False
336    False
337    False
338    False
339    False
340    False
341    False
342    False
343    False
344    False
345    False
346    False
347    False
348    False
349    False
350    False
351    False
352    False
353    False
354    False
355    False
356    False
357    False
358    False
359    False
360    False
361    False
362    False
363    False
364    False
Name: temp, dtype: bool

In [45]:
hot_days= df[df["temp"] > 30]

In [46]:
hot_days.head()

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
125,dehradun,2015-05-06,38.9,20.9,30.5,36.7,20.9,29.8,11.5,34.0,...,27.2,10,NaN,2015-05-06T05:30:48,2015-05-06T18:58:33,0.58,Clear,Clear conditions throughout the day.,clear-day,"42111099999,remote"
126,dehradun,2015-05-07,39.7,23.2,31.5,37.7,23.2,30.8,12.0,32.7,...,27.0,10,NaN,2015-05-07T05:29:59,2015-05-07T18:59:13,0.61,Clear,Clear conditions throughout the day.,clear-day,"42111099999,remote"
127,dehradun,2015-05-08,40.2,23.7,31.4,37.9,23.7,30.6,11.6,32.5,...,25.8,9,NaN,2015-05-08T05:29:12,2015-05-08T18:59:52,0.65,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"42111099999,remote"
128,dehradun,2015-05-09,39.4,23.7,31.7,37.9,23.7,30.8,11.2,30.7,...,25.7,10,NaN,2015-05-09T05:28:26,2015-05-09T19:00:32,0.68,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"42111099999,remote"
129,dehradun,2015-05-10,39.7,24.4,31.9,39.2,24.4,31.5,12.8,33.4,...,25.5,9,NaN,2015-05-10T05:27:41,2015-05-10T19:01:11,0.72,Partially cloudy,Becoming cloudy in the afternoon.,partly-cloudy-day,"42111099999,remote"

In [47]:
hot_days.shape

(48, 33)

In [48]:
hot_days.info()

<class 'pandas.DataFrame'>
Index: 48 entries, 125 to 184
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              48 non-null     str
 1   datetime          48 non-null     str
 2   tempmax           48 non-null     float64
 3   tempmin           48 non-null     float64
 4   temp              48 non-null     float64
 5   feelslikemax      48 non-null     float64
 6   feelslikemin      48 non-null     float64
 7   feelslike         48 non-null     float64
 8   dew               48 non-null     float64
 9   humidity          48 non-null     float64
 10  precip            48 non-null     float64
 11  precipprob        48 non-null     int64
 12  precipcover       48 non-null     float64
 13  preciptype        16 non-null     str
 14  snow              48 non-null     int64
 15  snowdepth         48 non-null     int64
 16  windgust          48 non-null     float64
 17  windspeed         48 non-null     float64
 18  winddir           48 non-null     float64
 19  sealevelpressure  48 non-null     float64
 20  cloudcover        48 non-null     float64
 21  visibility        48 non-null     float64
 22  solarradiation    48 non-null     float64
 23  solarenergy       48 non-null     float64
 24  uvindex           48 non-null     int64
 25  severerisk        0 non-null      float64
 26  sunrise           48 non-null     str
 27  sunset            48 non-null     str
 28  moonphase         48 non-null     float64
 29  conditions        48 non-null     str
 30  description       48 non-null     str
 31  icon              48 non-null     str
 32  stations          48 non-null     str
dtypes: float64(20), int64(4), str(9)
memory usage: 19.3 KB